module.exports = (pageObjects, entries) => {
    pageObjects
    .waitForElementVisible('@machine', 5000)
    .click('@machine')
    .waitForElementVisible('@machine', 5000)
    .click('@machineType')
    .waitForElementVisible('@Year', 5000)
    .click('@Year')
    .click('@actualYear')
    .waitForElementVisible('@Make', 5000)
    .click('@Make')
    .click('@actualMake')
    .waitForElementVisible('@Model', 5000)
    .click('@Model')
    .click('@actualModel')
    .waitForElementVisible('@Result5', 5000)
    .click('@Item2')
    .waitForElementVisible('@addCartBtn',5000)
    .expect.element('@productQty').value.to.contain("1")
    pageObjects
    .waitForElementVisible('@addCartBtn', 5000)
    .click('@addCartBtn')
    .waitForElementVisible('@Popup', 5000)
    .click('@Popup')
    .waitForElementNotVisible('@Popup', 5000)
    .click('@cartBtn')
    .waitForElementVisible('@Result8', 5000)
    .expect.element('@qtyField').value.to.contain('1')
    pageObjects
    .waitForElementVisible('@checkoutBtn', 5000)
    .click('@checkoutBtn')
    .waitForElementVisible('@Result9', 5000)
    .setValue('@address1', entries.address1)
    .setValue('@zipCode', entries.zipCode)
    .setValue('@City', entries.City)
    .click('@State')
    .click('@shippingBtn')
    .waitForElementVisible('@useAnywayBtn', 5000)
    .click('@useAnywayBtn')
    .waitForElementVisible('@paymentBtn', 5000)
    .api.pause(500)
    pageObjects
    .click('@paymentBtn')
    .waitForElementVisible('@cardNum', 5000)
    .setValue('@cardNum', entries.cardNum)
    .click('@cardMonth')
    .click('@cardYear')
    .waitForElementVisible('@securityCode', 5000)
    .setValue('@securityCode', entries.securityCode)
    .clearValue('@email')
    .setValue('@email', entries.email)
    .setValue('@phoneNumber', entries.phoneNumber)
    .waitForElementVisible('@reviewOrderBtn', 5000)
    .click('@reviewOrderBtn')
    .waitForElementVisible('@errorMessage', 5000)
}